### ISSUE TITLE
Error in last cell 

### ISSUE THREAD

**Issue by Glup30** [TheLastBen/fast-stable-diffusion#2077]
I was using automatic 1111 a couple of hours before and now when i run the last cell i got this error message: 
any chance i can fix this?

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
    skip.click(
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'

**Comment by TheLastBen** [comment]
use the latest notebook

**Comment by ShunKaiser** [comment]
> use the latest notebook

I still approached the problem when using the latest notebook.

**Comment by podolyanbogdan** [comment]
> use the latest notebook

where i can find it?

**Comment by Glup30** [comment]
> use the latest notebook

I was using the notebook that was in your github, is that it?

**Comment by protrading104** [comment]
Confirmed. The latest version from GitHub is giving an error.

![image](https://user-images.githubusercontent.com/71656833/235510401-3490275d-ed49-42c7-9cbd-55578b3d6282.png)

![image](https://user-images.githubusercontent.com/71656833/235510473-fe39772a-3fe5-40a3-882d-796d0085eddd.png)

**Comment by buckwheaton** [comment]
I"m getting a different last cell error - using latest notebook: 

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

**Comment by TheLastBen** [comment]
@buckwheaton use a fresh sd folder

**Comment by TheLastBen** [comment]
@protrading104 
![a11](https://user-images.githubusercontent.com/110583491/235520196-157e7475-27f8-4972-a1b8-ee05b2ebd781.JPG)
it works fine

**Comment by HaikenEdge** [comment]
> @protrading104 ![a11](https://user-images.githubusercontent.com/110583491/235520196-157e7475-27f8-4972-a1b8-ee05b2ebd781.JPG) it works fine

I'm using the link out of the GitHub and I'm still getting the same error as @protrading104 even after clearing my cache. Do I just need to do a fresh install?

**Comment by NicoHuve** [comment]
I'm on the latest notebook but seem to have the same issue as OP (Also tried ona fresh sd folder).

ControlNet v1.1.125
Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt: 43c90409bd4493ea9f4734a166fc6180913f97cef4f69a2b7883edf700779693
Loading weights [43c90409bd] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Creating model from config: /content/gdrive/MyDrive/sd/stablediffusion/configs/stable-diffusion/v2-inference-v.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 26.8s (calculate hash: 9.5s, load weights from disk: 10.6s, find config: 2.7s, create model: 0.2s, apply weights to model: 1.9s, apply half(): 0.9s, move model to device: 1.0s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
    skip.click(
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'

**Comment by Maxadox** [comment]
same here

**Comment by hidecreature** [comment]
I'm using the lastest automatic1111 notebook and I get the same error. I'm trying to run Deliberate from civitai page using this link https://civitai.com/api/download/models/15236
![image](https://user-images.githubusercontent.com/125917050/235539072-ed932f68-85e2-43c6-9397-a4b574da1faf.png)

**Comment by PinheiroXD** [comment]
I've reinstalled it 4 times and it still gives me the same error. Any solution?

**Comment by Khayoon** [comment]
Same here tried to reinstall a few times which usually fixes this error, deleted the controlnet folder causing the bulk or errors

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
    skip.click(
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'
```

**Comment by CookieZ01** [comment]
same error,with the last notebook.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
    skip.click(
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'

**Comment by Hoozzych** [comment]
Same error here, even after a new sd folder

**Comment by mattedgett** [comment]
Same issue here. Empty google drive, new SD folder, latest notebook. I still get the error that ends with "TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'"

Thanks for any help on this one!

**Comment by hidecreature** [comment]
I think it is 'cause of the gradio version or its dependencies.. I have tried unchecking the "Use_Latest_Working_Commit" box and the notebook works like normal. idk.

**Comment by HaikenEdge** [comment]
> I think it is 'cause of the gradio version or its dependencies.. I have tried unchecking the "Use_Latest_Working_Commit" box and the notebook works like normal. idk.

NGL, did not see the solution coming. Guess I was so used to using the latest working commit that I didn't think it wasn't an option to uncheck it.

**Comment by TheLastBen** [comment]
Fixed

**Comment by basuketto111** [comment]
Hello

I was getting the same error as above until a few hours ago.

Now I tried to start it and it works!

Thanks!

**Comment by Glup30** [comment]
i'm still have the same error,idk what else to do

TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after

**Comment by Glup30** [comment]
Okay, this work for me : After the automaic 1111 cell i added this code 

%cd /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/
!git checkout master
!git reset --hard

idk why it works but it does, sadly i delete the sd folder before trying this, but now it works.

**Comment by Khayoon** [comment]
> %cd /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/
> !git checkout master
> !git reset --hard

Didnt work for me same error

> sadly i delete the sd folder before trying this

Next time rename it or just hold on to the embedding, LoRa and SDModel folders and styles.csv (the file for saved prompts)

**Comment by Glup30** [comment]
> > %cd /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/
> > !git checkout master
> > !git reset --hard
> 
> Didnt work for me same error
> 
> > sadly i delete the sd folder before trying this
> 
> Next time rename it or just hold on to the embedding, LoRa and SDModel folders and styles.csv (the file for saved prompts)

i unchecked the Use_Latest_Working_Commit then i put the code below
