### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'Dropdown'

### ISSUE THREAD

**Issue by Flaxmore** [TheLastBen/fast-stable-diffusion#2286]
after the update the colab realy don't want me to start stable diffusion. i keep getting this error.

**Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 42, in <module>
    from modules.call_queue import wrap_gradio_gpu_call, wrap_queued_call, queue_lock  # noqa: F401
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 5, in <module>
    from modules import shared, progress, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 16, in <module>
    from modules import localization, script_loading, errors, ui_components, shared_items, cmd_args
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_components.py", line 9, in <module>
    gr.Dropdown.get_expected_parent = FormComponent.get_expected_parent
AttributeError: module 'gradio' has no attribute 'Dropdown'**

**Comment by TheLastBen** [comment]
are you sure you're using the latest notebook ? https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by KuzeyVural** [comment]
@TheLastBen the first running was ok but after that it get that error again. Using latest, fresh install.

**Comment by omar3737** [comment]
> are you sure you're using the latest notebook ? https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

yes

**Comment by TheLastBen** [comment]
how to reproduce the error ?

**Comment by TheLastBen** [comment]
@Flaxmore https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb use directly this link

**Comment by Flaxmore** [comment]
> @Flaxmore https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb use directly this link

nothing changed

**Comment by djwashout** [comment]
Also having this issue.

**Comment by sajoukourckan** [comment]
Same having this issue also.

**Comment by profcat2** [comment]
I resolved this issue by deleting my SD folder and reinstalling using the latest notebook, I'm able to get into gradio but.... I'm now getting the file not found error, which there is an open ticket for.

Images will start to generate but they just crash at the end..

**Comment by hntrssthmpsn** [comment]
Looks likely to be related to this upstream commit: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/394ffa7b0a7fff3ec484bcd084e673a8b301ccc8#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efR83

I found it all runs correctly using if I update the cell where we check out the automatic1111 repo to use commit baf6946e06249c5af9851c60171692c44ef633e0 which I think corresponds to the last non-RC release. It may be fine to use the RC commit but I haven't checked. 

For a quick fix, just updated the tail end of the second cell to check out the earlier commit and remove the hard reset & pull like so to get back in action:

```
with capture.capture_output() as cap:
  %cd /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/
  !git checkout baf6946e06249c5af9851c60171692c44ef633e0
  #!git reset --hard
  #!git checkout master
  time.sleep(1)
  !rm webui.sh
  #!git pull
  ```

**Comment by Flaxmore** [comment]
> Looks likely to be related to this upstream commit: [AUTOMATIC1111/stable-diffusion-webui@394ffa7#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efR83](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/394ffa7b0a7fff3ec484bcd084e673a8b301ccc8#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efR83)
> 
> I found it all runs correctly using if I update the cell where we check out the automatic1111 repo to use commit baf6946e06249c5af9851c60171692c44ef633e0 which I think corresponds to the last non-RC release. It may be fine to use the RC commit but I haven't checked.
> 
> For a quick fix, just updated the tail end of the second cell to check out the earlier commit and remove the hard reset & pull like so to get back in action:
> 
> ```
> with capture.capture_output() as cap:
>   %cd /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/
>   !git checkout baf6946e06249c5af9851c60171692c44ef633e0
>   #!git reset --hard
>   #!git checkout master
>   time.sleep(1)
>   !rm webui.sh
>   #!git pull
> ```

Dont know still dosnt work

**Comment by Azura-13** [comment]
Having same issue

**Comment by Flaxmore** [comment]
i think that for me is the fact that i have a lot of lora and the colab version can't load them all at once if there was only a way to make them load slower so the whole colab don't collapse

**Comment by YANSANSEI** [comment]
First run is OK.Only first.
Having same issue.

**Comment by YANSANSEI** [comment]
> First run is OK.Only first. No LORA. Having same issue.

directly the link is good.
no errer
thank you

**Comment by virtualdmns** [comment]
i was getting this issue also, and was able to resolve it by starting with a fresh sd folder. it may have been because i had certain extensions installed. i think sd cn vid2vid was one of them. i also had a lot of lora files. issue is resolved now tho. this was on runpod btw.

**Comment by djwashout** [comment]
interesting... I still have all my extensions, loras, but I had to get rid of my checkpoint files and copy over only the checkpoint file I'm currently using. I had a bunch of checkpoint files and I think it was overwhelming, or perhaps one was corrupt? IDK. I loaded saved settings file but it didn't restore my settings. Wish there was a way to save my settings so I could restore a backup of the settings and not have to set everything back up again after each install. ohh well, no biggie. I'm still thankful for all those who work hard to provide us with this great tool! Thanks everyone for the hard work!
