### ISSUE TITLE
Can't upload caption files (RunPod)

### ISSUE THREAD

**Issue by M7md42** [TheLastBen/fast-stable-diffusion#2316]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File /workspace/mainrunpodDreamboothv1.py:512, in uplder.<locals>.up(Upload)
    510 uploader.close()
    511 Upload.close()
--> 512 upld(Remove_existing_instance_images, Crop_images, Crop_size, IMAGES_FOLDER_OPTIONAL, INSTANCE_DIR, CAPTIONS_DIR, uploader, ren)
    513 done()

File /workspace/mainrunpodDreamboothv1.py:579, in upld(Remove_existing_instance_images, Crop_images, Crop_size, IMAGES_FOLDER_OPTIONAL, INSTANCE_DIR, CAPTIONS_DIR, uploader, ren)
    577   if filename.split(".")[-1]=="txt":
    578     with open(CAPTIONS_DIR+'/'+filename, 'w') as f:
--> 579         f.write(file['content'].decode())            
    580   up=[file for file in uploader.value if filename.split(".")[-1]!="txt"]
    581 if Crop_images:

AttributeError: 'memoryview' object has no attribute 'decode'

**Comment by TheLastBen** [comment]
fixed, you don't need to update anything

**Comment by M7md42** [comment]
Thanks for your response, but it's still not working.

  |█              | 1/14 Uploaded
---------------------------------------------------------------------------
UnidentifiedImageError                    Traceback (most recent call last)
File /workspace/mainrunpodDreamboothv1.py:512, in uplder.<locals>.up(Upload)
    510 uploader.close()
    511 Upload.close()
--> 512 upld(Remove_existing_instance_images, Crop_images, Crop_size, IMAGES_FOLDER_OPTIONAL, INSTANCE_DIR, CAPTIONS_DIR, uploader, ren)
    513 done()

File /workspace/mainrunpodDreamboothv1.py:608, in upld(Remove_existing_instance_images, Crop_images, Crop_size, IMAGES_FOLDER_OPTIONAL, INSTANCE_DIR, CAPTIONS_DIR, uploader, ren)
    606 for file in tqdm(uploader.value, bar_format='  |{bar:15}| {n_fmt}/{total_fmt} Uploaded'):
    607     filename = file['name']
--> 608     img = Image.open(io.BytesIO(file['content']))
    610     extension = filename.split(".")[-1]
    611     identifier=filename.split(".")[0]   

File /usr/local/lib/python3.10/dist-packages/PIL/Image.py:3186, in open(fp, mode, formats)
   3184 for message in accept_warnings:
   3185     warnings.warn(message)
-> 3186 raise UnidentifiedImageError(
   3187     "cannot identify image file %r" % (filename if filename else fp)
   3188 )

UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f12c8970720>

**Comment by TheLastBen** [comment]
that's an issue with the image file, try a different dataset
