### ISSUE TITLE
Colab error

### ISSUE THREAD

**Issue by bhealey609** [TheLastBen/fast-stable-diffusion#2892]
Started consistently getting the following error running the Start Stable-Diffusion tab. Previously this would happen occasionally and simply restarting that section would fix it, but now it happens every time with or without the tunnel option checked. Any ideas?

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 39, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 18, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 8, in <module>
    import modules.textual_inversion.dataset
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/dataset.py", line 12, in <module>
    from modules import devices, shared, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 22, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 5, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 3, in <module>
    import k_diffusion.sampling
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/augmentation.py", line 6, in <module>
    from skimage import transform
  File "/usr/local/lib/python3.10/dist-packages/skimage/_shared/lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/skimage/transform/__init__.py", line 4, in <module>
    from .radon_transform import (radon, iradon, iradon_sart,
  File "/usr/local/lib/python3.10/dist-packages/skimage/transform/radon_transform.py", line 6, in <module>
    from ._warps import warp
  File "/usr/local/lib/python3.10/dist-packages/skimage/transform/_warps.py", line 9, in <module>
    from ..measure import block_reduce
  File "/usr/local/lib/python3.10/dist-packages/skimage/measure/__init__.py", line 2, in <module>
    from ._marching_cubes_lewiner import marching_cubes
  File "/usr/local/lib/python3.10/dist-packages/skimage/measure/_marching_cubes_lewiner.py", line 7, in <module>
    from ._marching_cubes_classic import _marching_cubes_classic
  File "/usr/local/lib/python3.10/dist-packages/skimage/measure/_marching_cubes_classic.py", line 3, in <module>
    from . import _marching_cubes_classic_cy
ImportError: cannot import name '_marching_cubes_classic_cy' from partially initialized module 'skimage.measure' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/skimage/measure/__init__.py)

**Comment by Mortilis** [comment]
Same

**Comment by mcqx4** [comment]
Got the same error.
Try to write this command above the Start Stable Diffusion cell:

!pip install --upgrade scikit-image

It worked for me

**Comment by HaikenEdge** [comment]
> Got the same error. Try to write this command above the Start Stable Diffusion cell:
> 
> !pip install --upgrade scikit-image
> 
> It worked for me

This seems to be the current solution.

**Comment by da-art-fantasy** [comment]
Thank you mcqx4,

It also worked for me.

**Comment by aifantasyglam** [comment]
It worked, thanks a lot, I'm just curious why this error appeared...?

![image](https://github.com/user-attachments/assets/4c5114a9-a88c-4c13-8fe0-b3a8e9a95213)

**Comment by HaikenEdge** [comment]
The hotfix by @mcqx4 stopped working; I'm now getting the following error with the hotfix:

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 162, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 52, in webui
    initialize.initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 74, in initialize
    initialize_rest(reload_script_modules=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 102, in initialize_rest
    sd_models.list_models()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 165, in list_models
    model_list = modelloader.load_models(model_path=model_path, model_url=model_url, command_path=shared.cmd_opts.ckpt_dir, ext_filter=[".ckpt", ".safetensors"], download_name="v1-5-pruned-emaonly.safetensors", ext_blacklist=[".vae.ckpt", ".vae.safetensors"], hash_prefix=expected_sha256)
TypeError: load_models() got an unexpected keyword argument 'hash_prefix'`

**Comment by aifantasyglam** [comment]
> The hotfix by @mcqx4 stopped working; I'm now getting the following error with the hotfix:
> 

Still working, have you tried Last Ben original notebook....?! 
https://github.com/TheLastBen/fast-stable-diffusion?tab=readme-ov-file

**Comment by HaikenEdge** [comment]
> > The hotfix by @mcqx4 stopped working; I'm now getting the following error with the hotfix:
> 
> Still working, have you tried Last Ben original notebook....?! https://github.com/TheLastBen/fast-stable-diffusion?tab=readme-ov-file

I refreshed to make sure it was the newest version of the notebook, got the original error, applied @mcqx4 's hotfix and then got the new error.

Also, does this even support Colab Pro anymore? I see a notebook for Paperspace, but not one for Colab Pro.

**Comment by aifantasyglam** [comment]
> > > The hotfix by @mcqx4 stopped working; I'm now getting the following error with the hotfix:
> > 
> > 
> > Still working, have you tried Last Ben original notebook....?! https://github.com/TheLastBen/fast-stable-diffusion?tab=readme-ov-file
> 
> I refreshed to make sure it was the newest version of the notebook, got the original error, applied @mcqx4 's hotfix and then got the new error.
> 
> Also, does this even support Colab Pro anymore? I see a notebook for Paperspace, but not one for Colab Pro.

Is working for me, and I use colab pro

you have to use this

![image](https://github.com/user-attachments/assets/f7a21f1c-6157-484e-98d4-9a5285a9b0cf)

**Comment by HaikenEdge** [comment]
> > > > The hotfix by @mcqx4 stopped working; I'm now getting the following error with the hotfix:
> > > 
> > > 
> > > Still working, have you tried Last Ben original notebook....?! https://github.com/TheLastBen/fast-stable-diffusion?tab=readme-ov-file
> > 
> > 
> > I refreshed to make sure it was the newest version of the notebook, got the original error, applied @mcqx4 's hotfix and then got the new error.
> > Also, does this even support Colab Pro anymore? I see a notebook for Paperspace, but not one for Colab Pro.
> 
> Is working for me, and I use colab pro
> 
> you have to use this
> 
> ![image](https://private-user-images.githubusercontent.com/162564405/352704631-f7a21f1c-6157-484e-98d4-9a5285a9b0cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjI0MTQsIm5iZiI6MTcyMjA2MjExNCwicGF0aCI6Ii8xNjI1NjQ0MDUvMzUyNzA0NjMxLWY3YTIxZjFjLTYxNTctNDg0ZS05OGQ0LTlhNTI4NWE5YjBjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwNjM1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWFlMjMwZTgyMWNlNGY5NWRhNWJkMjhkNTU1NDI0Mjc2NDA4ODIyMzM4MzZlZDQ0ZWM2NmExZGIwYmY1ZjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DAY280QbHP0qbDjVfZKUsTyAumCM_e8gf0wZY8GygyY)

Even with the controlnet module, I'm still getting the error with the hotfix.

**Comment by aifantasyglam** [comment]
> > > > > The hotfix by @mcqx4 stopped working; I'm now getting the following error with the hotfix:
> > > > 
> > > > 
> > > > Still working, have you tried Last Ben original notebook....?! https://github.com/TheLastBen/fast-stable-diffusion?tab=readme-ov-file
> > > 
> > > 
> > > I refreshed to make sure it was the newest version of the notebook, got the original error, applied @mcqx4 's hotfix and then got the new error.
> > > Also, does this even support Colab Pro anymore? I see a notebook for Paperspace, but not one for Colab Pro.
> > 
> > 
> > Is working for me, and I use colab pro
> > you have to use this
> > ![image](https://private-user-images.githubusercontent.com/162564405/352704631-f7a21f1c-6157-484e-98d4-9a5285a9b0cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjI0MTQsIm5iZiI6MTcyMjA2MjExNCwicGF0aCI6Ii8xNjI1NjQ0MDUvMzUyNzA0NjMxLWY3YTIxZjFjLTYxNTctNDg0ZS05OGQ0LTlhNTI4NWE5YjBjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwNjM1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWFlMjMwZTgyMWNlNGY5NWRhNWJkMjhkNTU1NDI0Mjc2NDA4ODIyMzM4MzZlZDQ0ZWM2NmExZGIwYmY1ZjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DAY280QbHP0qbDjVfZKUsTyAumCM_e8gf0wZY8GygyY)
> 
> Even with the controlnet module, I'm still getting the error with the hotfix.

I got this error some months ago, check this: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15167

**Comment by HaikenEdge** [comment]
> > > > > > The hotfix by @mcqx4 stopped working; I'm now getting the following error with the hotfix:
> > > > > 
> > > > > 
> > > > > Still working, have you tried Last Ben original notebook....?! https://github.com/TheLastBen/fast-stable-diffusion?tab=readme-ov-file
> > > > 
> > > > 
> > > > I refreshed to make sure it was the newest version of the notebook, got the original error, applied @mcqx4 's hotfix and then got the new error.
> > > > Also, does this even support Colab Pro anymore? I see a notebook for Paperspace, but not one for Colab Pro.
> > > 
> > > 
> > > Is working for me, and I use colab pro
> > > you have to use this
> > > ![image](https://private-user-images.githubusercontent.com/162564405/352704631-f7a21f1c-6157-484e-98d4-9a5285a9b0cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjI0MTQsIm5iZiI6MTcyMjA2MjExNCwicGF0aCI6Ii8xNjI1NjQ0MDUvMzUyNzA0NjMxLWY3YTIxZjFjLTYxNTctNDg0ZS05OGQ0LTlhNTI4NWE5YjBjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwNjM1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWFlMjMwZTgyMWNlNGY5NWRhNWJkMjhkNTU1NDI0Mjc2NDA4ODIyMzM4MzZlZDQ0ZWM2NmExZGIwYmY1ZjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DAY280QbHP0qbDjVfZKUsTyAumCM_e8gf0wZY8GygyY)
> > 
> > 
> > Even with the controlnet module, I'm still getting the error with the hotfix.
> 
> I got this error some months ago, check this: [AUTOMATIC1111/stable-diffusion-webui#15167](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15167)

Thanks for that, but that's just way too complicated for my dinosaur brain to figure out. I'll wait for an update to make it easier to deal with.

**Comment by aifantasyglam** [comment]
> > > > > > > The hotfix by @mcqx4 stopped working; I'm now getting the following error with the hotfix:
> > > > > > 
> > > > > > 
> > > > > > Still working, have you tried Last Ben original notebook....?! https://github.com/TheLastBen/fast-stable-diffusion?tab=readme-ov-file
> > > > > 
> > > > > 
> > > > > I refreshed to make sure it was the newest version of the notebook, got the original error, applied @mcqx4 's hotfix and then got the new error.
> > > > > Also, does this even support Colab Pro anymore? I see a notebook for Paperspace, but not one for Colab Pro.
> > > > 
> > > > 
> > > > Is working for me, and I use colab pro
> > > > you have to use this
> > > > ![image](https://private-user-images.githubusercontent.com/162564405/352704631-f7a21f1c-6157-484e-98d4-9a5285a9b0cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjI0MTQsIm5iZiI6MTcyMjA2MjExNCwicGF0aCI6Ii8xNjI1NjQ0MDUvMzUyNzA0NjMxLWY3YTIxZjFjLTYxNTctNDg0ZS05OGQ0LTlhNTI4NWE5YjBjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwNjM1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWFlMjMwZTgyMWNlNGY5NWRhNWJkMjhkNTU1NDI0Mjc2NDA4ODIyMzM4MzZlZDQ0ZWM2NmExZGIwYmY1ZjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DAY280QbHP0qbDjVfZKUsTyAumCM_e8gf0wZY8GygyY)
> > > 
> > > 
> > > Even with the controlnet module, I'm still getting the error with the hotfix.
> > 
> > 
> > I got this error some months ago, check this: [AUTOMATIC1111/stable-diffusion-webui#15167](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15167)
> 
> Thanks for that, but that's just way too complicated for my dinosaur brain to figure out. I'll wait for an update to make it easier to deal with.

don´t worry, just need to use this line above the Start Stable Diffusion cell: !pip install --upgrade spandrel_extra_arches spandrel

![image](https://github.com/user-attachments/assets/68fc4142-58c5-41e8-9c98-70405e959e55)

**Comment by HaikenEdge** [comment]
> !pip install --upgrade spandrel_extra_arches spandrel

Tried that, didn't solve the problem.

**Comment by aifantasyglam** [comment]
> > !pip install --upgrade spandrel_extra_arches spandrel
> 
> Tried that, didn't solve the problem.

did you kept the previous solution like this...?
both are required

![image](https://github.com/user-attachments/assets/b39ce617-9904-47e0-aa83-b67d70a8493f)

**Comment by HaikenEdge** [comment]
> > > !pip install --upgrade spandrel_extra_arches spandrel
> > 
> > 
> > Tried that, didn't solve the problem.
> 
> did you kept the previous solution like this...? both are required
> 
> ![image](https://private-user-images.githubusercontent.com/162564405/352706126-b39ce617-9904-47e0-aa83-b67d70a8493f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjQyMjEsIm5iZiI6MTcyMjA2MzkyMSwicGF0aCI6Ii8xNjI1NjQ0MDUvMzUyNzA2MTI2LWIzOWNlNjE3LTk5MDQtNDdlMC1hYTgzLWI2N2Q3MGE4NDkzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwNzA1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjEzOGMzZTg4YjgwMWI5OGY5NTQzZDAzYTNiNjZiM2FhZDhkZWJjNGU3MzhkNzYyMzBkNjQ0NjdhNDI5Yzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jWiFB6P4bTVXd1C2bXZAB_jLHLwYATYIreb-iWRffxI)

Previously had to two reversed, tried it your way, still didn't solve the problem.

**Comment by aifantasyglam** [comment]
> > > > !pip install --upgrade spandrel_extra_arches spandrel
> > > 
> > > 
> > > Tried that, didn't solve the problem.
> > 
> > 
> > did you kept the previous solution like this...? both are required
> > ![image](https://private-user-images.githubusercontent.com/162564405/352706126-b39ce617-9904-47e0-aa83-b67d70a8493f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjQyMjEsIm5iZiI6MTcyMjA2MzkyMSwicGF0aCI6Ii8xNjI1NjQ0MDUvMzUyNzA2MTI2LWIzOWNlNjE3LTk5MDQtNDdlMC1hYTgzLWI2N2Q3MGE4NDkzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwNzA1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjEzOGMzZTg4YjgwMWI5OGY5NTQzZDAzYTNiNjZiM2FhZDhkZWJjNGU3MzhkNzYyMzBkNjQ0NjdhNDI5Yzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jWiFB6P4bTVXd1C2bXZAB_jLHLwYATYIreb-iWRffxI)
> 
> Previously had to two reversed, tried it your way, still didn't solve the problem.

is weird...

**Comment by HaikenEdge** [comment]
> > > > > !pip install --upgrade spandrel_extra_arches spandrel
> > > > 
> > > > 
> > > > Tried that, didn't solve the problem.
> > > 
> > > 
> > > did you kept the previous solution like this...? both are required
> > > ![image](https://private-user-images.githubusercontent.com/162564405/352706126-b39ce617-9904-47e0-aa83-b67d70a8493f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjQyMjEsIm5iZiI6MTcyMjA2MzkyMSwicGF0aCI6Ii8xNjI1NjQ0MDUvMzUyNzA2MTI2LWIzOWNlNjE3LTk5MDQtNDdlMC1hYTgzLWI2N2Q3MGE4NDkzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwNzA1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjEzOGMzZTg4YjgwMWI5OGY5NTQzZDAzYTNiNjZiM2FhZDhkZWJjNGU3MzhkNzYyMzBkNjQ0NjdhNDI5Yzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jWiFB6P4bTVXd1C2bXZAB_jLHLwYATYIreb-iWRffxI)
> > 
> > 
> > Previously had to two reversed, tried it your way, still didn't solve the problem.
> 
> is weird...
> 
> did you tried marking this: Use_Cloudflare_Tunnel ?

Tried that, didn't solve the issue either. Thank though.

**Comment by kaitas** [comment]
@HaikenEdge 
it may work for you!

!pip install lmdb
!pip uninstall scikit-image
!pip install scikit-image

**Comment by HaikenEdge** [comment]
> @HaikenEdge it may work for you!
> 
> !pip install lmdb !pip uninstall scikit-image !pip install scikit-image

Unfortunately, that didn't solve the problem either.

**Comment by coder-xiaotian** [comment]
same

**Comment by BlessedDuelOP** [comment]
Hello, good day. I’m also having the same problem. I solved it by running the cell !pip install --upgrade scikit-image. I can generate images of 640x960, however, when I try to apply a hiresfix, I get the following error: 
![ERROR](https://github.com/user-attachments/assets/b869c469-c949-4035-b001-8d27c37c18af)

I have always been able to apply hiresfix at that resolution for a long time; I think it might be an error with xformers that is no longer present, but I’m not sure. I would greatly appreciate the help.

**Comment by CosmoKramer108** [comment]
> Is working for me, and I use colab pro
> 
> you have to use this
> 
> ![image](https://private-user-images.githubusercontent.com/162564405/352704631-f7a21f1c-6157-484e-98d4-9a5285a9b0cf.png?

How do I open or use this link? Back then with the short cut from Ben I came directly to the google interface.

**Comment by aifantasyglam** [comment]
> > Is working for me, and I use colab pro
> > you have to use this
> > ![image](https://private-user-images.githubusercontent.com/162564405/352704631-f7a21f1c-6157-484e-98d4-9a5285a9b0cf.png?
> 
> How do I open or use this link? Back then with the short cut from Ben I came directly to the google interface.

download this file:
![image](https://github.com/user-attachments/assets/3f65c62c-81b3-4f58-8b9f-aa4f1f8de640)

and upload it here:
https://colab.research.google.com/

**Comment by aionrevenge** [comment]
!pip install --upgrade spandrel_extra_arches spandrel
!pip install --upgrade scikit-image

it's worked, thank you guys

**Comment by TheLastBen** [comment]
fixed, no need to add the pip install lines

**Comment by HaikenEdge** [comment]
> fixed, no need to add the pip install lines

I'm glad you fixed it, but I've tried refreshing to notebook to get the latest version and I've tried using the download @aifantasyglam specified, but I'm still getting the error. Do I need to delete the contents of my SD folder or something?

**Comment by junwoochoi2** [comment]
> > fixed, no need to add the pip install lines
> 
> I'm glad you fixed it, but I've tried refreshing to notebook to get the latest version and I've tried using the download @aifantasyglam specified, but I'm still getting the error. Do I need to delete the contents of my SD folder or something?

You already know answer.

**Comment by aifantasyglam** [comment]
> > fixed, no need to add the pip install lines
> 
> I'm glad you fixed it, but I've tried refreshing to notebook to get the latest version and I've tried using the download @aifantasyglam specified, but I'm still getting the error. Do I need to delete the contents of my SD folder or something?

same situation

**Comment by CosmoKramer108** [comment]
> and upload it here: https://colab.research.google.com/

I get an "Unexpected token" error.

**Comment by HaikenEdge** [comment]
> > fixed, no need to add the pip install lines
> 
> I'm glad you fixed it, but I've tried refreshing to notebook to get the latest version and I've tried using the download @aifantasyglam specified, but I'm still getting the error. Do I need to delete the contents of my SD folder or something?

Apparently, had to delete everything and reinstall, which I was hoping to avoid.

**Comment by aifantasyglam** [comment]
> > > fixed, no need to add the pip install lines
> > 
> > 
> > I'm glad you fixed it, but I've tried refreshing to notebook to get the latest version and I've tried using the download @aifantasyglam specified, but I'm still getting the error. Do I need to delete the contents of my SD folder or something?
> 
> Apparently, had to delete everything and reinstall, which I was hoping to avoid. Working now.

Oh I see, I tried the updated file, and now is working
![image](https://github.com/user-attachments/assets/1933fc71-bb5a-4198-a587-d7c2b6aaa9d0)

**Comment by HaikenEdge** [comment]
> > > > fixed, no need to add the pip install lines
> > > 
> > > 
> > > I'm glad you fixed it, but I've tried refreshing to notebook to get the latest version and I've tried using the download @aifantasyglam specified, but I'm still getting the error. Do I need to delete the contents of my SD folder or something?
> > 
> > 
> > Apparently, had to delete everything and reinstall, which I was hoping to avoid. Working now.
> 
> Oh I see, I tried the updated file, and now is working ![image](https://private-user-images.githubusercontent.com/162564405/352930687-1933fc71-bb5a-4198-a587-d7c2b6aaa9d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzMzMDAsIm5iZiI6MTcyMjIzMzAwMCwicGF0aCI6Ii8xNjI1NjQ0MDUvMzUyOTMwNjg3LTE5MzNmYzcxLWJiNWEtNDE5OC1hNTg3LWQ3YzJiNmFhYTlkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwNjAzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzZiNzA5ZWQ3MDhkZDEyZmFiYTA2ZjUwZjk3NDkxZGQyYTIxZDI3NDBlMmY2ZDFkMmUxMGQ1YmViMTM0ZDZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tWC-lRBvVRPhyL0OeC4BvtlilFksuTVY0m-GcaD0gSs)

I tried that yesterday after it had been updated and it didn't fix it, which is why I had to nuke the folder.

**Comment by aifantasyglam** [comment]
> > > > > fixed, no need to add the pip install lines
> > > > 
> > > > 
> > > > I'm glad you fixed it, but I've tried refreshing to notebook to get the latest version and I've tried using the download @aifantasyglam specified, but I'm still getting the error. Do I need to delete the contents of my SD folder or something?
> > > 
> > > 
> > > Apparently, had to delete everything and reinstall, which I was hoping to avoid. Working now.
> > 
> > 
> > Oh I see, I tried the updated file, and now is working ![image](https://private-user-images.githubusercontent.com/162564405/352930687-1933fc71-bb5a-4198-a587-d7c2b6aaa9d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzMzMDAsIm5iZiI6MTcyMjIzMzAwMCwicGF0aCI6Ii8xNjI1NjQ0MDUvMzUyOTMwNjg3LTE5MzNmYzcxLWJiNWEtNDE5OC1hNTg3LWQ3YzJiNmFhYTlkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwNjAzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzZiNzA5ZWQ3MDhkZDEyZmFiYTA2ZjUwZjk3NDkxZGQyYTIxZDI3NDBlMmY2ZDFkMmUxMGQ1YmViMTM0ZDZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tWC-lRBvVRPhyL0OeC4BvtlilFksuTVY0m-GcaD0gSs)
> 
> I tried that yesterday after it had been updated and it didn't fix it, which is why I had to nuke the folder.

yes, I did the same, but I tried some minutes ago and now is working, I think that maybe is required to wait some minutes or hours to get the file refreshed

**Comment by HaikenEdge** [comment]
> > > > > > fixed, no need to add the pip install lines
> > > > > 
> > > > > 
> > > > > I'm glad you fixed it, but I've tried refreshing to notebook to get the latest version and I've tried using the download @aifantasyglam specified, but I'm still getting the error. Do I need to delete the contents of my SD folder or something?
> > > > 
> > > > 
> > > > Apparently, had to delete everything and reinstall, which I was hoping to avoid. Working now.
> > > 
> > > 
> > > Oh I see, I tried the updated file, and now is working ![image](https://private-user-images.githubusercontent.com/162564405/352930687-1933fc71-bb5a-4198-a587-d7c2b6aaa9d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzMzMDAsIm5iZiI6MTcyMjIzMzAwMCwicGF0aCI6Ii8xNjI1NjQ0MDUvMzUyOTMwNjg3LTE5MzNmYzcxLWJiNWEtNDE5OC1hNTg3LWQ3YzJiNmFhYTlkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwNjAzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzZiNzA5ZWQ3MDhkZDEyZmFiYTA2ZjUwZjk3NDkxZGQyYTIxZDI3NDBlMmY2ZDFkMmUxMGQ1YmViMTM0ZDZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tWC-lRBvVRPhyL0OeC4BvtlilFksuTVY0m-GcaD0gSs)
> > 
> > 
> > I tried that yesterday after it had been updated and it didn't fix it, which is why I had to nuke the folder.
> 
> yes, I did the same, but I tried some minutes ago and now is working, I think that maybe is required to wait some minutes or hours to get the file refreshed

Don't know if that's actually the case, since I uploaded the notebook, ran it, errored, killed the Colab, renamed the SD folder, ran notebook again and it was working immediately.

**Comment by aifantasyglam** [comment]
Hello everyone, regarding the problem mentioned in this thread, have anyone had this kind of issue using "reactor"...?

`2024-07-30 07:15:53.006386379 [E:onnxruntime:Default, provider_bridge_ort.cc:1745 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory`

![image](https://github.com/user-attachments/assets/98262a46-8aea-44c5-bb23-5a8e03116cdd)
