### ISSUE TITLE
Fast-Dreambooth Google Colab error

### ISSUE THREAD

**Issue by jeblbej** [TheLastBen/fast-stable-diffusion#2935]
Hello, I know that nowadays, Paperspace is the place to go to use this. But I am not possible to use Paperspace for free so I still work on Colab. Everything was OK (including inserting another jax in a cell) until today.
When I run model download cell (i am using a model stored on my gdisk), i get this error:

Detecting model version...
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-3-cb52de44df48>](https://localhost:8080/#) in <cell line: 149>()
    223     wget.download('https://github.com/TheLastBen/fast-stable-diffusion/raw/main/Dreambooth/det.py')
    224     print('Detecting model version...')
--> 225     Custom_Model_Version=check_output('python det.py '+sftnsr+' --MODEL_PATH '+str(MODEL_PATH), shell=True).decode('utf-8').replace('\n', '')
    226     clear_output()
    227     print(''+Custom_Model_Version+' Detected')

1 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    524         retcode = process.poll()
    525         if check and retcode:
--> 526             raise CalledProcessError(retcode, process.args,
    527                                      output=stdout, stderr=stderr)
    528     return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command 'python det.py --from_safetensors --MODEL_PATH /content/gdrive/MyDrive/modelyAI/epiCPhotoGasm.safetensors' returned non-zero exit status 1.

Can someone possibly help me? Thx in advance.

**Comment by m-andrew-reid** [comment]
I'm getting the same issue and error with models from an external link that have always worked before. This issue suddenly started within the last 48 hours.

**Comment by insidem4n** [comment]
Same issue too, i used this in the last 24hrs without any problems until now. 

Appreciate anyone with a fix or workaround.
Thanks

**Comment by Katsukipp** [comment]
> Hello, I know that nowadays, Paperspace is the place to go to use this. But I am not possible to use Paperspace for free so I still work on Colab. Everything was OK (including inserting another jax in a cell) until today. When I run model download cell (i am using a model stored on my gdisk), i get this error:
> 
> ## Detecting model version...
> CalledProcessError Traceback (most recent call last) in <cell line: 149>() 223 wget.download('https://github.com/TheLastBen/fast-stable-diffusion/raw/main/Dreambooth/det.py') 224 print('Detecting model version...') --> 225 Custom_Model_Version=check_output('python det.py '+sftnsr+' --MODEL_PATH '+str(MODEL_PATH), shell=True).decode('utf-8').replace('\n', '') 226 clear_output() 227 print(''+Custom_Model_Version+' Detected')
> 
> 1 frames [/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in run(input, capture_output, timeout, check, *popenargs, **kwargs) 524 retcode = process.poll() 525 if check and retcode: --> 526 raise CalledProcessError(retcode, process.args, 527 output=stdout, stderr=stderr) 528 return CompletedProcess(process.args, retcode, stdout, stderr)
> 
> CalledProcessError: Command 'python det.py --from_safetensors --MODEL_PATH /content/gdrive/MyDrive/modelyAI/epiCPhotoGasm.safetensors' returned non-zero exit status 1.
> 
> Can someone possibly help me? Thx in advance.

have you try download with "model downloader" extension in ui ?

**Comment by jeblbej** [comment]
> > Hello, I know that nowadays, Paperspace is the place to go to use this. But I am not possible to use Paperspace for free so I still work on Colab. Everything was OK (including inserting another jax in a cell) until today. When I run model download cell (i am using a model stored on my gdisk), i get this error:
> > ## Detecting model version...
> > CalledProcessError Traceback (most recent call last) in <cell line: 149>() 223 wget.download('https://github.com/TheLastBen/fast-stable-diffusion/raw/main/Dreambooth/det.py') 224 print('Detecting model version...') --> 225 Custom_Model_Version=check_output('python det.py '+sftnsr+' --MODEL_PATH '+str(MODEL_PATH), shell=True).decode('utf-8').replace('\n', '') 226 clear_output() 227 print(''+Custom_Model_Version+' Detected')
> > 1 frames [/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in run(input, capture_output, timeout, check, *popenargs, **kwargs) 524 retcode = process.poll() 525 if check and retcode: --> 526 raise CalledProcessError(retcode, process.args, 527 output=stdout, stderr=stderr) 528 return CompletedProcess(process.args, retcode, stdout, stderr)
> > CalledProcessError: Command 'python det.py --from_safetensors --MODEL_PATH /content/gdrive/MyDrive/modelyAI/epiCPhotoGasm.safetensors' returned non-zero exit status 1.
> > Can someone possibly help me? Thx in advance.
> 
> have you try download with "model downloader" extension in ui ?

Yes. It works but then i run to another problem in "Training section":

Training the UNet...
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/usr/local/lib/python3.10/dist-packages/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 33, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/usr/local/lib/python3.10/dist-packages/accelerate/tracking.py", line 34, in <module>
    import wandb
  File "/usr/local/lib/python3.10/dist-packages/wandb/__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/__init__.py", line 5, in <module>
    from . import wandb_helper as helper  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_helper.py", line 6, in <module>
    from .lib import config_util
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/config_util.py", line 9, in <module>
    from wandb.util import load_yaml
  File "/usr/local/lib/python3.10/dist-packages/wandb/util.py", line 53, in <module>
    import sentry_sdk  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/__init__.py", line 1, in <module>
    from sentry_sdk.hub import Hub, init
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/hub.py", line 9, in <module>
    from sentry_sdk.client import Client
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/client.py", line 25, in <module>
    from sentry_sdk.profiler import setup_profiler
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/profiler/__init__.py", line 1, in <module>
    from sentry_sdk.profiler.continuous_profiler import start_profiler, stop_profiler
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/profiler/continuous_profiler.py", line 12, in <module>
    from sentry_sdk.profiler.utils import (
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/profiler/utils.py", line 4, in <module>
    from sentry_sdk._compat import PY311
ImportError: cannot import name 'PY311' from 'sentry_sdk._compat' (/usr/local/lib/python3.10/dist-packages/sentry_sdk/_compat.py)
Something went wrong

**Comment by jeblbej** [comment]
Anyone solved this issue?

**Comment by m-andrew-reid** [comment]
It appears not. Is your model a .safetensor or a .ckpt? It's not working for me with .safetensor from an external link.

**Comment by jeblbej** [comment]
> It appears not. Is your model a .safetensor or a .ckpt? It's not working for me with .safetensor from an external link.

.safetensor. But this is really not an issue of the model at all. Something must have changed. The training itself is broken too. As I mentioned above.

**Comment by TheLastBen** [comment]
it should work now, make sure you used the latest notebook

**Comment by zassoulich** [comment]
Still not working for me. Second cell gets stuck at "  !pip uninstall diffusers -qq" indefinetely.
