### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by aidankrk** [TheLastBen/fast-stable-diffusion#2938]
Receiving the following error during training in the fast dreambooth Colab notebook, unsure what to do:

Training the UNet...
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 18, in <module>
    from diffusers import AutoencoderKL, DDPMScheduler, StableDiffusionPipeline, UNet2DConditionModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 27, in <module>
    from .pipelines import OnnxRuntimeModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/__init__.py", line 18, in <module>
    from .dance_diffusion import DanceDiffusionPipeline
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/dance_diffusion/__init__.py", line 1, in <module>
    from .pipeline_dance_diffusion import DanceDiffusionPipeline
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py", line 21, in <module>
    from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 39, in <module>
    from ..models.modeling_utils import _LOW_CPU_MEM_USAGE_DEFAULT
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/__init__.py", line 20, in <module>
    from .controlnet import ControlNetModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/controlnet.py", line 32, in <module>
    from .unet_2d_condition import UNet2DConditionModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 22, in <module>
    from ..loaders import UNet2DConditionLoadersMixin
  File "/usr/local/lib/python3.10/dist-packages/diffusers/loaders/__init__.py", line 3, in <module>
    from ..utils import DIFFUSERS_SLOW_IMPORT, _LazyModule, deprecate
ImportError: cannot import name 'DIFFUSERS_SLOW_IMPORT' from 'diffusers.utils' (/usr/local/lib/python3.10/dist-packages/diffusers/utils/__init__.py)
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ftkrz', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ftkrz/instance_images', '--output_dir=/content/models/ftkrz', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ftkrz/captions', '--instance_prompt=', '--seed=179211', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=1500']' returned non-zero exit status 1.
Something went wrong

**Comment by smithee77** [comment]
Same here, seems to be s/t new in last couple days, it was working ok last week? :(

**Comment by SoumiaSiYoucef** [comment]
same her, the training and testing both don't work, in this notebook: fast-DreamBooth.ipynb
although few days ago they were working perfectly. @TheLastBen

**Comment by SoumiaSiYoucef** [comment]
whenever an error is fixed a new appear: 
**cannot import name 'CpuOffload' from 'accelerate.hooks'
cannot import name 'PY311' from 'sentry_sdk._compat
cannot import name 'DIFFUSERS_SLOW_IMPORT' from 'diffusers.utils'** @TheLastBen

**Comment by abdelrahman-elasfar** [comment]
I have the same issue

**Comment by TheLastBen** [comment]
will check it out

**Comment by SoumiaSiYoucef** [comment]
Yes pleas, thank u so much, waiting.

**Comment by TheLastBen** [comment]
fixed, use the latest notebook

**Comment by aidankrk** [comment]
> fixed, use the latest notebook

Thanks so much, I really appreciate all the assistance you provide.

Unfortunately I'm still having some issues in the updated notebook. 
When installing dependencies, I find it's stuck at line 8 " !pip uninstall diffusers -qq"

I reverted to the old code from an earlier version I had saved which fixed the dependencies, however I receive a new error during training: 

Training the UNet...
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 18, in <module>
    from diffusers import AutoencoderKL, DDPMScheduler, StableDiffusionPipeline, UNet2DConditionModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 27, in <module>
    from .pipelines import OnnxRuntimeModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/__init__.py", line 18, in <module>
    from .dance_diffusion import DanceDiffusionPipeline
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/dance_diffusion/__init__.py", line 1, in <module>
    from .pipeline_dance_diffusion import DanceDiffusionPipeline
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py", line 21, in <module>
    from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 39, in <module>
    from ..models.modeling_utils import _LOW_CPU_MEM_USAGE_DEFAULT
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/__init__.py", line 20, in <module>
    from .controlnet import ControlNetModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/controlnet.py", line 32, in <module>
    from .unet_2d_condition import UNet2DConditionModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 22, in <module>
    from ..loaders import UNet2DConditionLoadersMixin
  File "/usr/local/lib/python3.10/dist-packages/diffusers/loaders/__init__.py", line 3, in <module>
    from ..utils import DIFFUSERS_SLOW_IMPORT, _LazyModule, deprecate
ImportError: cannot import name 'DIFFUSERS_SLOW_IMPORT' from 'diffusers.utils' (/usr/local/lib/python3.10/dist-packages/diffusers/utils/__init__.py)
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/s1h7e', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/s1h7e/instance_images', '--output_dir=/content/models/s1h7e', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/s1h7e/captions', '--instance_prompt=', '--seed=378939', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=1500']' returned non-zero exit status 1.
Something went wrong

If there is any recommendation or a fix please let me know - again thank you for your assistance

**Comment by SoumiaSiYoucef** [comment]
i believe "!pip uninstall diffusers -qq" is waiting for "yes" to uninstall, as --qq is for quit mode, so you can't see the question to confirm uninstallation. @aidankrk

**Comment by SoumiaSiYoucef** [comment]
Thank you so much @TheLastBen for your assistance.

**Comment by SoumiaSiYoucef** [comment]
Unfortunattely, testing is not working: i get this error: 

**Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 460, in create_ui
    with gr.Blocks(analytics_enabled=False) as txt2img_interface:
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 486, in __init__
    super().__init__(render=False, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 274, in __init__
    super().__init__(visible=visible, render=render, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 80, in __init__
    check_deprecated_parameters(self.__class__.__name__, **kwargs)
TypeError: check_deprecated_parameters() missing 1 required keyword-only argument: 'kwargs'### Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 460, in create_ui
    with gr.Blocks(analytics_enabled=False) as txt2img_interface:
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 486, in __init__
    super().__init__(render=False, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 274, in __init__
    super().__init__(visible=visible, render=render, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 80, in __init__
    check_deprecated_parameters(self.__class__.__name__, **kwargs)
TypeError: check_deprecated_parameters() missing 1 required keyword-only argument: 'kwargs'**

**Comment by aidankrk** [comment]
@SoumiaSiYoucef 
Thank you, I also changed to !pip uninstall diffusers -y and it worked. I was also able to do training successfully. Thank you again @TheLastBen

**Comment by SoumiaSiYoucef** [comment]
yes, thanks to @TheLastBen ,but the testing with an previous trained model do not work :/

**Comment by TheLastBen** [comment]
ok, fixed, use the latest notebook
