### ISSUE TITLE
SD 1.5 Conversion error 

### ISSUE THREAD

**Issue by limetones** [TheLastBen/fast-stable-diffusion#2942]
1.5 Detected
[1;32mSession found, loading the trained model ...
Traceback (most recent call last):
  File "/content/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py", line 19, in <module>
    from diffusers.pipelines.stable_diffusion.convert_from_ckpt import download_from_original_stable_diffusion_ckpt
  File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 27, in <module>
    from .pipelines import OnnxRuntimeModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/__init__.py", line 18, in <module>
    from .dance_diffusion import DanceDiffusionPipeline
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/dance_diffusion/__init__.py", line 1, in <module>
    from .pipeline_dance_diffusion import DanceDiffusionPipeline
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py", line 21, in <module>
    from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 39, in <module>
    from ..models.modeling_utils import _LOW_CPU_MEM_USAGE_DEFAULT
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/__init__.py", line 20, in <module>
    from .controlnet import ControlNetModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/controlnet.py", line 32, in <module>
    from .unet_2d_condition import UNet2DConditionModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 22, in <module>
    from ..loaders import UNet2DConditionLoadersMixin
  File "/usr/local/lib/python3.10/dist-packages/diffusers/loaders/__init__.py", line 3, in <module>
    from ..utils import DIFFUSERS_SLOW_IMPORT, _LazyModule, deprecate
ImportError: cannot import name 'DIFFUSERS_SLOW_IMPORT' from 'diffusers.utils' (/usr/local/lib/python3.10/dist-packages/diffusers/utils/__init__.py)
Conversion error, if the error persists, remove the CKPT file from the current session folder

**Comment by TheLastBen** [comment]
fixed

**Comment by limetones** [comment]
Hi, it seems the problem is still there, i am trying to load a previous session, it giving me the same error.

**Comment by limetones** [comment]
Thanks a ton bro! You are the best!
