### ISSUE TITLE
Model not downloading!

### ISSUE THREAD

**Issue by BlenderProxy** [TheLastBen/fast-stable-diffusion#3093]
Cant Download models bc they dont exist anymore?

![Image](https://github.com/user-attachments/assets/8e28baa8-8e09-452b-b7c7-5e49211fd352)

**Comment by BlenderProxy** [comment]
fixed! using https://huggingface.co/RedbeardNZ/stable-diffusion-2-1-base

**Comment by dave27652** [comment]
i am seeing the same thing for v2-1_768-ema-pruned.safetensors on hugging face. page does not exist.

nice you got it working. but the issue remains that the OFFICIAL source for the base model no longer exists (assuming i am not making an error of some kind)
