### ISSUE TITLE
dreambooth xformers installation error

### ISSUE THREAD

**Issue by lumariobob90009** [TheLastBen/fast-stable-diffusion#41]
Hi, ran into this during the xformers install cell run:

!pip install triton==2.0.0.dev20220701!wc -l < /content/xformers/setup.py >num

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: -l

**Comment by TheLastBen** [comment]
just fixed,
I'm in the process of optimizing the layout, so you might encounter some errors

**Comment by FAOlivieri** [comment]
When I reach the "Start DreamBooth" step, it gives this error:

**Comment by TheLastBen** [comment]
yes I just fixed it, wait a minute and reload the colab from the repo

**Comment by eukleshnin** [comment]
Hi! Thank you for your work! 
Still seeing the error, even with the updated repo. Do I need to clean the installation somehow?

**Comment by TheLastBen** [comment]
disconnect the colab runtime and relaunch the colab from the main repo page

**Comment by 1blackbar** [comment]
i ran it on colab pro and goes well, now trying free colab as well and they both work so far! I just wish i could give it a proper path to my model in gradio ui instead of letting it find it on its own by giving name, i dont have it in default folders as i use google shareddrives not mydrive ( cause space runs out quickly on mydrive) so i have to edit the cell code each time

**Comment by TheLastBen** [comment]
I will add the option of a custom folder, meanwhile you can edit the Gradio cell and change the path manually
