### ISSUE TITLE
Py3d_tools

### ISSUE THREAD

**Issue by cerarslan** [TheLastBen/fast-stable-diffusion#744]
I just want share my issue bcs maybe somebody face this issue before. I know I'm very newbie around but I tried several methods such as change path. However I don't understand what's that problem coming keep from my face. Btw I can perfcetly controlling others stuffs. Thanks for everbody already! 

Open
[AssertionError: extension access disabed because of commandline flags](https://github.com/TheLastBen/fast-stable-diffusion/issues/725#top)
#725
[cerarslan](https://github.com/cerarslan) opened this issue 18 hours ago · 2 comments
Comments
[cerarslan](https://github.com/cerarslan) commented [18 hours ago](https://github.com/TheLastBen/fast-stable-diffusion/issues/725#issue-1467236749)
I was able to install extensions on local server but I was getting ModuleNotFoundError: No module named 'py3d_tools'. Now I can't install any extension through Gradio and I get this error. Can you help me ?

Error completing request
Arguments: ('', 'https://github.com/deforum-art/deforum-for-automatic1111-webui.git') {}
Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
res = list(func(*args, **kwargs))
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extensions.py", line 111, in install_extension_from_url
check_access()
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extensions.py", line 20, in check_access
assert not shared.cmd_opts.disable_extension_access, "extension access disabed because of commandline flags"
AssertionError: extension access disabed because of commandline flags

[TheLastBen](https://github.com/TheLastBen) commented [11 hours ago](https://github.com/TheLastBen/fast-stable-diffusion/issues/725#issuecomment-1330153277)
Check the box "use_gradio_server" then try again

[cerarslan](https://github.com/cerarslan) commented [4 hours ago](https://github.com/TheLastBen/fast-stable-diffusion/issues/725#issuecomment-1330653147)
So much thanks @TheLastBen it works but I get 'py3d' erorr again :( Can you want to look at?

File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
res = list(func(*args, **kwargs))
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
res = func(*args, **kwargs)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 231, in run_deforum
processed = DeforumScript.run(None, p, override_settings_with_file, custom_settings_file, animation_mode, max_frames, border, angle, zoom, translation_x, translation_y, translation_z, rotation_3d_x, rotation_3d_y, rotation_3d_z, flip_2d_perspective, perspective_flip_theta, perspective_flip_phi, perspective_flip_gamma, perspective_flip_fv, noise_schedule, strength_schedule, contrast_schedule, cfg_scale_schedule, fov_schedule, near_schedule, far_schedule, seed_schedule, color_coherence, diffusion_cadence, use_depth_warping, midas_weight, near_plane, far_plane, fov, padding_mode, sampling_mode, save_depth_maps, video_init_path, extract_nth_frame, overwrite_extracted_frames, use_mask_video, video_mask_path, interpolate_key_frames, interpolate_x_frames, resume_from_timestring, resume_timestring, prompts, animation_prompts, W, H, restore_faces, tiling, enable_hr, firstphase_width, firstphase_height, seed, sampler, seed_enable_extras, subseed, subseed_strength, seed_resize_from_w, seed_resize_from_h, steps, ddim_eta, n_batch, make_grid, grid_rows, save_settings, save_samples, display_samples, save_sample_per_step, show_sample_per_step, override_these_with_webui, batch_name, filename_format, seed_behavior, use_init, from_img2img_instead_of_link, strength_0_no_init, strength, init_image, use_mask, use_alpha_as_mask, invert_mask, overlay_mask, mask_file, mask_contrast_adjust, mask_brightness_adjust, mask_overlay_blur, fill, full_res_mask, full_res_mask_padding, skip_video_for_run_all, fps, output_format, ffmpeg_location, add_soundtrack, soundtrack_path, use_manual_settings, render_steps, max_video_frames, path_name_modifier, image_path, mp4_path, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14, i15, i16, i17, i18, i19, i20, i21, i22, i23, i24, i25, i26, i27, i28, i29, i30, i31, i32, i33, i34, i35, i36)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 63, in run
from scripts.deforum_helpers.render import render_animation, render_input_video, render_animation_with_video_mask, render_interpolation
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/render.py", line 13, in
from .generate import generate, add_noise
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/generate.py", line 24, in
from .animation import sample_from_cv2, sample_to_cv2
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/animation.py", line 5, in
import py3d_tools as p3d
ModuleNotFoundError: No module named 'py3d_tools'

**Comment by TheLastBen** [comment]
I'll work on it very soon

**Comment by cerarslan** [comment]
Yes! Thank you sir.

**Comment by cerarslan** [comment]
Sir any goodnews? 🙏🏿 I try every solution, i mean i m literally try 😂 @TheLastBen

**Comment by TheLastBen** [comment]
fixed

**Comment by cerarslan** [comment]
I fixed the problem just right before you did.  Thank you legendary Ben, I appreciate it!

**Comment by CJohnDesign** [comment]
What was the fix here? I'm still getting it. 

I tried to change the extension folder name to just `deforum` and that gave me a new error: `ModuleNotFoundError: No module named 'scripts.deforum_helpers.render'`

Then I started and its back to the same error

**Comment by CJohnDesign** [comment]
What was the fix here? I'm still getting it.

I tried to change the extension folder name to just deforum and that gave me a new error: ModuleNotFoundError: No module named 'scripts.deforum_helpers.render'

Then I restarted and its back to the same error: `ModuleNotFoundError: No module named 'py3d_tools'`

**Comment by CJohnDesign** [comment]
I've done both - I'm still getting the error.

**Comment by TheLastBen** [comment]
after installing deforum for the first time, re-run the cell "requirements" to apply the fix

**Comment by CJohnDesign** [comment]
Looks like that cell gets stuck when I click it the second time - it spins forever. No logs output. 

Going to try a few more times.

**Comment by CJohnDesign** [comment]
Well, good new/bad news, I got a new error: `ImportError: cannot import name 'get_frame_name' from 'scripts.deforum_helpers.animation' (/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/animation.py)`

**Comment by TheLastBen** [comment]
probably the script got updated, I'll update it shortly

**Comment by TheLastBen** [comment]
re-run the "requirements" cell, it should work now

**Comment by CJohnDesign** [comment]
Progress but another error even after a fresh install: `NameError: name 'hashlib' is not defined`

**Comment by TheLastBen** [comment]
!pip install hashlib

**Comment by CJohnDesign** [comment]
I see the new commit you pushed (adding hashlib) but getting the same error. When I add a new cell with `!pip install hashlib`, I get this:
```
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting hashlib
  Using cached hashlib-20081119.zip (42 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/74/bb/9003d081345e9f0451884146e9ea2cff6e4cc4deac9ffd4a9ee98b318a49/hashlib-20081119.zip#sha256=419de2fd10ae71ed9c6adcb55903f116abd1d8acc8c814dfd5f839b4d5013e38 (from https://pypi.org/simple/hashlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement hashlib (from versions: 20081119)
ERROR: No matching distribution found for hashlib
```

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by TheLastBen** [comment]
fixed, forgot to add "import hashlib" (a built-in dep)

**Comment by CJohnDesign** [comment]
Up and running! Thanks Ben

**Comment by CJohnDesign** [comment]
New error:

```
Error loading script: deforum.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 12, in <module>
    import deforum_helpers.args as deforum_args
ModuleNotFoundError: No module named 'deforum_helpers'
```

**Comment by CJohnDesign** [comment]
I feel like this commit could be the culprit: https://github.com/deforum-art/deforum-for-automatic1111-webui/commit/0ede3a83da5dee80a094a3bc75d3493008072bfe

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by CJohnDesign** [comment]
Not so lucky. Thanks, Ben 👍
