### ISSUE TITLE
Conversion error, Insufficient RAM or corrupt CKPT, use a 4.7GB CKPT instead of 7GB

### ISSUE THREAD

**Issue by ReEnMikki** [TheLastBen/fast-stable-diffusion#765]
Conversion error, Insufficient RAM or corrupt CKPT, use a 4.7GB CKPT instead of 7GB

Tried multiple different models, even ones from weeks ago, even tried checking Compatibility_Mode, but this error keeps popping up.

**Comment by barrand** [comment]
I'm getting this error as well, even with ckpt models under 4gb. I've tried two different models uploaded to google drive and I get the same error.

This is the link I'm using. Is this correct?

**Comment by TheLastBen** [comment]
It's all fixed now, refresh the colab and the error will not appear anymore

**Comment by sqzhang-jeremy** [comment]
> It's all fixed now [33e7c7f](https://github.com/TheLastBen/fast-stable-diffusion/commit/33e7c7f605e9b1f53bf4c4e7ae2be14d1183a25d), refresh the colab and the error will not appear anymore

Actually, It still doesn't work for https://github.com/TheLastBen/fast-stable-diffusion/commit/33e7c7f605e9b1f53bf4c4e7ae2be14d1183a25d, and then I use the latest version https://github.com/TheLastBen/fast-stable-diffusion/tree/b6c1d9d992357e13788f12e502d3eda32d19717b. Finally, it works for me!

**Comment by TheLastBen** [comment]
That is the latest version, but use this link instead : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb
